---
apiVersion: v1
kind: Namespace
metadata:
  name: demo

---
apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: demo
  labels:
    app.kubernetes.io/name: demo
spec:
  containers:
  - name: demo
    image: docker.io/library/__IMAGE__ 
    ports:
      - containerPort: __PORT__
        name: http
        
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: demo
spec:
  selector:
    app.kubernetes.io/name: demo
  ports:
  - name: demo
    protocol: TCP
    port: __PORT__
    targetPort: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: demo.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-service
                port:
                  number: __PORT__
