apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: demo
  labels:
    app.kubernetes.io/name: demo
spec:
  containers:
  - name: demo
    image: docker.io/library/__IMAGE__ 
    ports:
      - containerPort: __PORT__
        name: http
        
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: demo
spec:
  selector:
    app.kubernetes.io/name: demo
  ports:
  - name: demo
    protocol: TCP
    port: __PORT__
    targetPort: http

